# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Have you mooed today?
email:            david+site@indava.com
description:      'David Flores'
baseurl:          '' # The subpath of your site, e.g. /blog
url:              '' # The base hostname & protocol for your site
github_username:  dmouse
twitter_username: dmouse

markdown:  kramdown
permalink: pretty
paginate:  12

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-feed

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             David Flores
    bio:              ''
    gravatar:         https://avatars0.githubusercontent.com/u/198571?v=4
    email:            david+site@indava.com
    website:          http://dmouse.net
    github_username:  dmouse
    twitter_username: dmouse
